### ISSUE TITLE
Simulator never plays Lookout

### ISSUE THREAD

**Issue by chadeos** [rspeer/dominiate#85]
in makeCard "Lookout",

      ai_playValue: (state, my) ->
        if state.gainsToEndGame >= 5 or state.cardInfo.Curse in my.draw
          895
        else
          -5

It should say

        if state.gainsToEndGame() >= 5 or state.cardInfo.Curse in my.draw

since state.gainsToEndGame is a function. [Source](http://forum.dominionstrategy.com/index.php?topic=619.msg486204#msg486204)

**Comment by rspeer** [comment]
Fixed! Thanks for the bug report. I'll see if I can get to more of these as well.
